package org.forgesworn.charter

import android.app.admin.DevicePolicyManager
import android.content.Context
import android.os.UserManager
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.forgesworn.charter.admin.Provisioning
import org.forgesworn.charter.enforce.DpmAppGateOps
import org.forgesworn.charter.enforce.DpmRestrictionOps
import org.forgesworn.charter.enforce.FakeDnsFilterOps
import org.forgesworn.charter.enforce.UsageSource
import org.forgesworn.charter.native.CharterCore
import org.forgesworn.charter.service.WardenController
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * The load-bearing e2e (port-spec §6.3): on the emulator provisioned as Device
 * Owner, a real guardian-signed clause drives the shared Rust core, and the
 * decision produces a REAL DevicePolicyManager suspension + install-lockdown.
 * Proves T1 (install lockdown), T2-analog (signed clause → enact), T4 (suspend
 * gate), and the inert-before-charter inverse (I17).
 *
 * The fixture is generated by `android/jni/examples/gen_fixture.rs` — a paused
 * schedule signed by the pinned test guardian, so the assertion is time-free.
 */
@RunWith(AndroidJUnit4::class)
class EnforcementE2ETest {

    private val context: Context get() = ApplicationProvider.getApplicationContext()
    private lateinit var dpm: DevicePolicyManager
    private val admin get() = Provisioning.adminComponent(context)

    // From: cargo run --example gen_fixture
    private val guardian = "defdea4cdb677750a420fee807eacf21eb9898ae79b9768766e4faa04a2d4a34"
    private val subject = "70e6b44a2ac6083ab673bacb5cb7ca554b795b416e702c1c980bb7b87c78b8e9"
    private val pausedClause =
        """{"id":"3a0bba59d85fa9eed40497dc5559e467dc584a5cb12cf51c52798042a07a3fbe","pubkey":"defdea4cdb677750a420fee807eacf21eb9898ae79b9768766e4faa04a2d4a34","created_at":1,"kind":31113,"tags":[["t","charter-device"],["d","schedule"]],"content":"{\"body\":{\"issuedAt\":1,\"paused\":true,\"tz\":\"Europe/London\",\"v\":1,\"weekly\":{}},\"issuedAt\":1,\"kind\":\"schedule\",\"subject\":\"70e6b44a2ac6083ab673bacb5cb7ca554b795b416e702c1c980bb7b87c78b8e9\",\"v\":1}","sig":"dc11662559bdb3b0d6a63877c04f58855da823cbc02b1822dec6761b700d0f70ceaa39b7b54bf52f06147ab21efd249b56c7948bc8927722c51120d295e7b4a2"}"""
    // Empty weekly → always allowed but still a charter (unlocked yet configured).
    private val openClause =
        """{"id":"cccf73d06e74c87652b3f29bd98ae0c670ac3ee5d19ec3cf78d10fab06981d87","pubkey":"defdea4cdb677750a420fee807eacf21eb9898ae79b9768766e4faa04a2d4a34","created_at":2,"kind":31113,"tags":[["t","charter-device"],["d","schedule"]],"content":"{\"body\":{\"issuedAt\":2,\"tz\":\"Europe/London\",\"v\":1,\"weekly\":{}},\"issuedAt\":2,\"kind\":\"schedule\",\"subject\":\"70e6b44a2ac6083ab673bacb5cb7ca554b795b416e702c1c980bb7b87c78b8e9\",\"v\":1}","sig":"22dc542fbbedba576612c4ff152e3d17f3b6256193fff4587aa2020d4e86e70c78b97e01316929e359dec39dd601a2d00598dc501e38e1fcd546c1be0759fa21"}"""

    @Before
    fun setUp() {
        dpm = Provisioning.dpm(context)
        // These assertions require Device Owner; the CI harness provisions it.
        assumeTrue("needs Device Owner (dpm set-device-owner)", Provisioning.isDeviceOwner(context))
        // Clean slate so re-runs are deterministic.
        java.io.File(Provisioning.baseDir(context)).deleteRecursively()
        runCatching { dpm.clearUserRestriction(admin, UserManager.DISALLOW_INSTALL_APPS) }
        // The install lock is both restrictions, so a deterministic re-run has to
        // clear both — a leftover unknown-sources block would fail the
        // inert-before-a-charter assertion for the wrong reason.
        runCatching { dpm.clearUserRestriction(admin, UserManager.DISALLOW_INSTALL_UNKNOWN_SOURCES) }
    }

    @Test
    fun abiVersionMatches() {
        assertEquals(1, CharterCore.abiVersion())
    }

    /**
     * A maintenance window's whole job is to let an install through. It cannot
     * do that by standing down `DISALLOW_INSTALL_APPS` alone: on GrapheneOS,
     * sandboxed Play is an unprivileged app and therefore an unknown source, so
     * a window that lifts one restriction and not the other opens visibly and
     * changes nothing a ward can see. Both move together, or the feature lies.
     */
    @Test
    fun theInstallLockIsBothRestrictionsTogether() {
        val restrictions = DpmRestrictionOps(dpm, admin)
        try {
            restrictions.setInstallLock(locked = true)
            assertTrue(
                "sessions must be closed",
                restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_APPS),
            )
            assertTrue(
                "unknown sources must be closed too",
                restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_UNKNOWN_SOURCES),
            )

            // The maintenance window: a store install must actually be possible.
            restrictions.setInstallLock(locked = false)
            assertFalse(
                "sessions must reopen inside the window",
                restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_APPS),
            )
            assertFalse(
                "unknown sources must reopen too, or sandboxed Play stays blocked",
                restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_UNKNOWN_SOURCES),
            )

            // And it must come back — the window shutting is the load-bearing half.
            restrictions.setInstallLock(locked = true)
            assertTrue(
                "sessions must re-close when the window shuts",
                restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_APPS),
            )
            assertTrue(
                "unknown sources must re-close when the window shuts",
                restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_UNKNOWN_SOURCES),
            )
        } finally {
            restrictions.clearBaseline()
        }
    }

    @Test
    fun signedClauseDrivesRealSuspensionAndInstallLockdown() {
        val core = CharterCore.init(Provisioning.baseDir(context), "enforce", Provisioning.ownVersionCode(context))
        assertTrue("init error: ${core.error}", core.error == null)

        // A never-suspend target for the deny-list; use a real system app as the
        // "ward app" stand-in — the calculator ships on the AOSP emulator.
        val wardApp = wardAppOnDevice()
        assumeTrue("no suspendable test app present", wardApp != null)

        val appGate = DpmAppGateOps(context, dpm, admin)
        val restrictions = DpmRestrictionOps(dpm, admin)
        val fakeUsage = object : UsageSource {
            override fun foregroundPackage() = subject
            override fun screenInteractive() = true
        }
        val lockCalls = mutableListOf<String>()
        val controller = WardenController(
            context, dpm, admin, appGate, restrictions, fakeUsage,
            org.forgesworn.charter.enforce.FakeApkInstallOps(),
            FakeDnsFilterOps(),
            object : WardenController.LockController {
                override fun show(reason: String) { lockCalls.add("show:$reason") }
                override fun hide() { lockCalls.add("hide") }
            },
        )
        controller.init()

        // Inert before any charter (I17): no install-lockdown yet.
        controller.tickAndApply(now())
        assertFalse(
            "install must NOT be locked down before a charter exists",
            restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_APPS),
        )

        // Ingest the real guardian-signed clause.
        CharterCore.setPairing(guardian, subject)
        val res = CharterCore.ingestClause(pausedClause, now())
        assertTrue("clause rejected: ${res.reason}", res.accepted)

        // Tick: the paused schedule → locked → real suspension + lock + lockdown.
        val decisions = controller.tickAndApply(now())
        assertTrue("core should report locked", decisions.first().locked)
        assertEquals("schedule", decisions.first().reason)

        // The REAL DevicePolicyManager effects:
        assertTrue(
            "ward app must be suspended (T4)",
            appGate.isSuspended(wardApp!!),
        )
        assertTrue(
            "install must be locked down once a charter exists (T1/I28)",
            restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_APPS),
        )
        assertTrue("lock surface should be raised", lockCalls.any { it.startsWith("show:") })

        // ---- the review's critical fix: restrictions stay up while UNLOCKED ----
        // Supersede the paused clause with an always-allowed one. The ward is now
        // charted but unlocked; the install-lockdown must NOT be torn down (before
        // the fix, an unlocked tick set hasCharter=false and cleared it).
        val open = CharterCore.ingestClause(openClause, now())
        assertTrue("open clause rejected: ${open.reason}", open.accepted)
        val openDecisions = controller.tickAndApply(now())
        assertFalse("ward should now be unlocked", openDecisions.first().locked)
        assertTrue("but still configured (charter exists)", openDecisions.first().configured)
        assertTrue(
            "install-lockdown MUST remain during allowed hours (the fail-open fix)",
            restrictions.isRestrictionActive(UserManager.DISALLOW_INSTALL_APPS),
        )
        assertFalse(
            "ward app must be unsuspended while unlocked",
            appGate.isSuspended(wardApp),
        )

        // Clean up so the emulator is left usable.
        appGate.reconcile(
            locked = false,
            appPolicy = null,
            ruleSuspensions = emptySet(),
            listeningExempt = emptySet(),
            bucketSuspensions = emptySet(),
        )
        restrictions.clearBaseline()
    }

    private fun now() = System.currentTimeMillis() / 1000

    /** A launchable, non-denylisted package we may suspend for the test. */
    private fun wardAppOnDevice(): String? {
        val deny = org.forgesworn.charter.enforce.denyListPackages(context)
        return org.forgesworn.charter.enforce.launchablePackages(context)
            .firstOrNull { it !in deny && it != context.packageName }
    }
}
