//! Whether the ward's app lock (fapolicyd with Kintrinsic's rules) is armed,
//! for STATUS `appLockArmed`.
//!
//! Arming and disarming are `charter-applock`'s job (root, opt-in, never on
//! install or upgrade — see `linux/packaging/setup/charter-applock`). charterd
//! only REPORTS it, and reports `true` only when every link that makes the
//! lock bite for every ward is present right now, so a guardian never reads
//! "armed" off a box where it is not:
//!
//! 1. the rendered rules file in `rules.d` is ours (first line carries the
//!    tag `charter-applock` writes),
//! 2. it covers EVERY current member of `charter-managed` (a ward added after
//!    arming, and not yet `charter-applock refresh`ed, is unlocked),
//! 3. `compiled.rules` — what fapolicyd actually loads — carries the ward
//!    default-deny,
//! 4. `fapolicyd.conf` is not permissive,
//! 5. a `fapolicyd` process is alive (`/run/fapolicyd.pid` → `/proc/<pid>/comm`),
//! 6. no ward can write near the top of a tree the rules trust by path (a
//!    cheap, two-level re-run of the arm-time audit; the full one is `arm`'s).
//!
//! Plain file reads and `lstat`s only (no exec per tick); anything unreadable
//! reads as "not armed", with the reason, which the loop logs on change.

use std::collections::BTreeSet;
use std::fs;
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};

/// First line of the rules file `charter-applock arm` renders. Mirrors
/// `GENERATED_TAG` in `charter-applock` — change both together.
pub const GENERATED_TAG: &str = "# generated by charter-applock";
/// The default-deny every rendered rules file carries. Mirrors `DENY_MARK`.
pub const DENY_MARK: &str = "deny_log perm=execute";
/// The group whose members are wards. Mirrors `MANAGED_GROUP`.
pub const MANAGED_GROUP: &str = "charter-managed";
/// Trees the rules allow a ward to execute from. Mirrors `ALLOWED_TREES`.
pub const ALLOWED_TREES: &[&str] = &[
    "/usr",
    "/etc",
    "/opt",
    "/snap",
    "/var/lib/flatpak",
    "/var/lib/charter/approved",
];

/// Everything the judgement reads, redirectable for tests.
#[derive(Debug, Clone)]
pub struct AppLockPaths {
    pub rules: PathBuf,
    pub compiled: PathBuf,
    pub conf: PathBuf,
    pub pid_file: PathBuf,
    pub proc_root: PathBuf,
    pub group: PathBuf,
    pub passwd: PathBuf,
    pub trees: Vec<PathBuf>,
}

impl Default for AppLockPaths {
    fn default() -> Self {
        Self {
            rules: "/etc/fapolicyd/rules.d/72-kintrinsic-applock.rules".into(),
            compiled: "/etc/fapolicyd/compiled.rules".into(),
            conf: "/etc/fapolicyd/fapolicyd.conf".into(),
            pid_file: "/run/fapolicyd.pid".into(),
            proc_root: "/proc".into(),
            group: "/etc/group".into(),
            passwd: "/etc/passwd".into(),
            trees: ALLOWED_TREES.iter().map(PathBuf::from).collect(),
        }
    }
}

/// The verdict, with why when it is `false`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AppLockReport {
    pub armed: bool,
    /// `None` when armed, or when the lock simply is not installed (the
    /// ordinary unarmed state, which is not worth a log line).
    pub reason: Option<String>,
}

impl AppLockReport {
    fn off() -> Self {
        Self {
            armed: false,
            reason: None,
        }
    }
    fn broken(reason: impl Into<String>) -> Self {
        Self {
            armed: false,
            reason: Some(reason.into()),
        }
    }
}

/// The rules file is the one `charter-applock` rendered.
pub fn rules_are_ours(rules: &str) -> bool {
    rules
        .lines()
        .next()
        .is_some_and(|l| l.starts_with(GENERATED_TAG))
}

/// The rendered rules hold the default-deny for this ward's uid.
pub fn rules_cover_uid(rules: &str, uid: u32) -> bool {
    let want = format!("{DENY_MARK} uid={uid} : all");
    rules.lines().any(|l| l.trim() == want)
}

/// fapolicyd would load a ward default-deny from this compiled rule set.
pub fn compiled_has_policy(compiled: &str) -> bool {
    compiled
        .lines()
        .any(|l| l.trim_start().starts_with(DENY_MARK))
}

/// `fapolicyd.conf` leaves fapolicyd ENFORCING: the last uncommented
/// `permissive = N` is 0, or there is none (fapolicyd's default is 0).
pub fn conf_is_enforcing(conf: &str) -> bool {
    let mut permissive: Option<&str> = None;
    for line in conf.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            if k.trim() == "permissive" {
                permissive = Some(v.trim());
            }
        }
    }
    matches!(permissive, None | Some("0"))
}

/// The wards: `(uids, gids)` — every member of `charter-managed` resolved
/// through the passwd file, and every group any of them is in (primary gid
/// plus supplementary memberships), for the writability check.
pub fn wards(group: &str, passwd: &str) -> (BTreeSet<u32>, BTreeSet<u32>) {
    let members: BTreeSet<&str> = group
        .lines()
        .filter_map(|l| {
            let f: Vec<&str> = l.splitn(4, ':').collect();
            (f.len() == 4 && f[0] == MANAGED_GROUP).then_some(f[3])
        })
        .flat_map(|m| m.split(','))
        .map(str::trim)
        .filter(|m| !m.is_empty())
        .collect();
    let mut uids = BTreeSet::new();
    let mut gids = BTreeSet::new();
    for l in passwd.lines() {
        let f: Vec<&str> = l.split(':').collect();
        if f.len() >= 4 && members.contains(f[0]) {
            if let (Ok(u), Ok(g)) = (f[2].parse(), f[3].parse()) {
                uids.insert(u);
                gids.insert(g);
            }
        }
    }
    for l in group.lines() {
        let f: Vec<&str> = l.splitn(4, ':').collect();
        if f.len() == 4 && f[3].split(',').any(|m| members.contains(m.trim())) {
            if let Ok(g) = f[2].parse() {
                gids.insert(g);
            }
        }
    }
    (uids, gids)
}

/// Could a ward write this entry? Owner is a ward, world-writable, or
/// group-writable by a group a ward is in.
pub fn ward_writable(
    uid: u32,
    gid: u32,
    mode: u32,
    uids: &BTreeSet<u32>,
    gids: &BTreeSet<u32>,
) -> bool {
    uids.contains(&uid) || mode & 0o002 != 0 || (mode & 0o020 != 0 && gids.contains(&gid))
}

/// The first entry within two levels of an allowed tree a ward could write,
/// if any. Symlinks are skipped: fapolicyd judges the resolved path.
fn shallow_tree_hit(
    trees: &[PathBuf],
    uids: &BTreeSet<u32>,
    gids: &BTreeSet<u32>,
) -> Option<PathBuf> {
    fn check(p: &Path, uids: &BTreeSet<u32>, gids: &BTreeSet<u32>) -> Option<bool> {
        let m = fs::symlink_metadata(p).ok()?;
        if m.file_type().is_symlink() {
            return Some(false);
        }
        Some(ward_writable(m.uid(), m.gid(), m.mode(), uids, gids))
    }
    for tree in trees {
        if check(tree, uids, gids) == Some(true) {
            return Some(tree.clone());
        }
        let Ok(level1) = fs::read_dir(tree) else {
            continue;
        };
        for e1 in level1.flatten() {
            let p1 = e1.path();
            match check(&p1, uids, gids) {
                Some(true) => return Some(p1),
                Some(false) => {}
                None => continue,
            }
            if !e1.file_type().is_ok_and(|t| t.is_dir()) {
                continue;
            }
            let Ok(level2) = fs::read_dir(&p1) else {
                continue;
            };
            for e2 in level2.flatten() {
                if check(&e2.path(), uids, gids) == Some(true) {
                    return Some(e2.path());
                }
            }
        }
    }
    None
}

/// Read the live system and judge every link.
pub fn probe(paths: &AppLockPaths) -> AppLockReport {
    let read = |p: &PathBuf| fs::read_to_string(p).ok();
    let Some(rules) = read(&paths.rules) else {
        return AppLockReport::off();
    };
    if !rules_are_ours(&rules) {
        return AppLockReport::broken(
            "the app-lock rules file is not the one charter-applock rendered",
        );
    }
    let (uids, gids) = wards(
        &read(&paths.group).unwrap_or_default(),
        &read(&paths.passwd).unwrap_or_default(),
    );
    if uids.is_empty() {
        return AppLockReport::broken("the app lock covers no ward (charter-managed is empty)");
    }
    if let Some(uid) = uids.iter().find(|u| !rules_cover_uid(&rules, **u)) {
        return AppLockReport::broken(format!(
            "ward uid {uid} is not covered by the app-lock rules (run: charter-applock refresh)"
        ));
    }
    if !read(&paths.compiled).is_some_and(|c| compiled_has_policy(&c)) {
        return AppLockReport::broken("the compiled fapolicyd rules do not carry the app lock");
    }
    if !read(&paths.conf).is_some_and(|c| conf_is_enforcing(&c)) {
        return AppLockReport::broken(
            "fapolicyd is configured permissive (or its config is unreadable)",
        );
    }
    let alive = read(&paths.pid_file)
        .and_then(|pid| pid.trim().parse::<u32>().ok())
        .and_then(|pid| fs::read_to_string(paths.proc_root.join(pid.to_string()).join("comm")).ok())
        .is_some_and(|comm| comm.trim() == "fapolicyd");
    if !alive {
        return AppLockReport::broken("fapolicyd is not running");
    }
    if let Some(hit) = shallow_tree_hit(&paths.trees, &uids, &gids) {
        return AppLockReport::broken(format!(
            "a ward can write {} inside a tree the app lock trusts by path",
            hit.display()
        ));
    }
    AppLockReport {
        armed: true,
        reason: None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;

    const RULES: &str = "# generated by charter-applock — do not edit\n# wards (uid): 1001\ndeny_log perm=execute uid=1001 : all\ndeny_log perm=execute auid=1001 : all\n";
    const COMPILED: &str = "## This file is automatically generated from /etc/fapolicyd/rules.d\nallow perm=execute uid=1001 : dir=/usr/\ndeny_log perm=execute uid=1001 : all\nallow perm=any all : all\n";
    const CONF: &str = "#\n# permissive = 1\npermissive = 0\ntrust = file\n";
    const GROUP: &str = "root:x:0:\nstaff:x:50:kid\ncharter-managed:x:990:kid\nkid:x:1001:\n";
    const PASSWD: &str = "root:x:0:0::/root:/bin/bash\nkid:x:1001:1001::/srv/kid:/bin/bash\n";

    struct Fixture {
        dir: PathBuf,
        paths: AppLockPaths,
    }

    impl Fixture {
        fn new(tag: &str) -> Self {
            let dir = std::env::temp_dir()
                .join(format!("charterd-app-lock-{tag}-{}", std::process::id()));
            let _ = fs::remove_dir_all(&dir);
            fs::create_dir_all(dir.join("proc/4242")).unwrap();
            fs::create_dir_all(dir.join("tree/bin")).unwrap();
            fs::set_permissions(dir.join("tree"), fs::Permissions::from_mode(0o755)).unwrap();
            fs::set_permissions(dir.join("tree/bin"), fs::Permissions::from_mode(0o755)).unwrap();
            let paths = AppLockPaths {
                rules: dir.join("rules"),
                compiled: dir.join("compiled"),
                conf: dir.join("conf"),
                pid_file: dir.join("pid"),
                proc_root: dir.join("proc"),
                group: dir.join("group"),
                passwd: dir.join("passwd"),
                trees: vec![dir.join("tree")],
            };
            fs::write(&paths.rules, RULES).unwrap();
            fs::write(&paths.compiled, COMPILED).unwrap();
            fs::write(&paths.conf, CONF).unwrap();
            fs::write(&paths.pid_file, "4242\n").unwrap();
            fs::write(dir.join("proc/4242/comm"), "fapolicyd\n").unwrap();
            fs::write(&paths.group, GROUP).unwrap();
            fs::write(&paths.passwd, PASSWD).unwrap();
            Self { dir, paths }
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.dir);
        }
    }

    #[test]
    fn every_link_present_is_armed() {
        let f = Fixture::new("ok");
        // The test tree is owned by whoever runs the test; make sure that is
        // not "a ward" for this fixture.
        let me = fs::metadata(&f.dir).unwrap().uid();
        assert_ne!(me, 1001, "run the tests as someone other than uid 1001");
        assert_eq!(
            probe(&f.paths),
            AppLockReport {
                armed: true,
                reason: None
            }
        );
    }

    #[test]
    fn no_rules_file_is_plainly_off() {
        let f = Fixture::new("off");
        fs::remove_file(&f.paths.rules).unwrap();
        assert_eq!(probe(&f.paths), AppLockReport::off());
    }

    #[test]
    fn each_missing_link_is_not_armed_and_says_why() {
        type Breaker = Box<dyn Fn(&AppLockPaths)>;
        let cases: Vec<(&str, Breaker)> = vec![
            (
                "not the one",
                Box::new(|p| fs::write(&p.rules, "allow perm=any all : all\n").unwrap()),
            ),
            (
                "uid 1002 is not covered",
                Box::new(|p| {
                    fs::write(&p.group, "charter-managed:x:990:kid,sib\n").unwrap();
                    fs::write(
                        &p.passwd,
                        format!("{PASSWD}sib:x:1002:1002::/srv/sib:/bin/bash\n"),
                    )
                    .unwrap();
                }),
            ),
            (
                "covers no ward",
                Box::new(|p| fs::write(&p.group, "charter-managed:x:990:\n").unwrap()),
            ),
            (
                "compiled",
                Box::new(|p| fs::write(&p.compiled, "allow perm=any all : all\n").unwrap()),
            ),
            (
                "permissive",
                Box::new(|p| fs::write(&p.conf, "permissive = 1\n").unwrap()),
            ),
            (
                "not running",
                Box::new(|p| fs::write(p.proc_root.join("4242/comm"), "bash\n").unwrap()),
            ),
            (
                "can write",
                Box::new(|p| {
                    fs::set_permissions(p.trees[0].join("bin"), fs::Permissions::from_mode(0o777))
                        .unwrap()
                }),
            ),
        ];
        for (why, break_it) in cases {
            let f = Fixture::new("broken");
            break_it(&f.paths);
            let r = probe(&f.paths);
            assert!(!r.armed, "{why}");
            let reason = r.reason.unwrap_or_default();
            assert!(reason.contains(why), "{why}: {reason}");
        }
    }

    #[test]
    fn permissive_parsing_follows_fapolicyd() {
        assert!(conf_is_enforcing("trust = file\n"), "absent defaults to 0");
        assert!(conf_is_enforcing("# permissive = 1\npermissive=0\n"));
        assert!(
            !conf_is_enforcing("permissive = 0\npermissive = 1\n"),
            "last wins"
        );
        assert!(!conf_is_enforcing("  permissive =  1  \n"));
    }

    #[test]
    fn wards_resolve_members_and_their_groups() {
        let (uids, gids) = wards(GROUP, PASSWD);
        assert_eq!(uids.into_iter().collect::<Vec<_>>(), vec![1001]);
        assert!(gids.contains(&1001) && gids.contains(&50) && gids.contains(&990));
        assert!(!gids.contains(&0));
    }

    #[test]
    fn writability_is_owner_world_or_ward_group() {
        let uids: BTreeSet<u32> = [1001].into();
        let gids: BTreeSet<u32> = [1001, 50].into();
        assert!(ward_writable(1001, 0, 0o755, &uids, &gids), "ward-owned");
        assert!(ward_writable(0, 0, 0o757, &uids, &gids), "world-writable");
        assert!(ward_writable(0, 50, 0o775, &uids, &gids), "ward's group");
        assert!(
            !ward_writable(0, 60, 0o775, &uids, &gids),
            "someone else's group"
        );
        assert!(!ward_writable(0, 0, 0o755, &uids, &gids));
    }

    #[test]
    fn rule_coverage_is_by_exact_default_deny_line() {
        assert!(rules_cover_uid(RULES, 1001));
        assert!(!rules_cover_uid(RULES, 100), "no prefix match");
        assert!(!rules_cover_uid(RULES, 1002));
    }

    /// The Rust constants and the shell script must agree, or charterd would
    /// report a correctly armed box as unarmed.
    #[test]
    fn constants_match_charter_applock() {
        let script = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../packaging/setup/charter-applock"),
        )
        .unwrap();
        assert!(script.contains(&format!("GENERATED_TAG=\"{GENERATED_TAG}\"")));
        assert!(script.contains(&format!("DENY_MARK=\"{DENY_MARK}\"")));
        assert!(script.contains(&format!("MANAGED_GROUP={MANAGED_GROUP}")));
        assert!(script.contains(&format!("ALLOWED_TREES=({})", ALLOWED_TREES.join(" "))));
        let d = AppLockPaths::default();
        assert!(script.contains(&format!(
            "RULES_DST=\"$FAPO_DIR/rules.d/{}\"",
            d.rules.file_name().unwrap().to_str().unwrap()
        )));
    }
}
