//! Whether the ward's app lock (fapolicyd with Kintrinsic's rules) is armed,
//! for STATUS `appLockArmed`.
//!
//! Arming and disarming are `charter-applock`'s job (root, opt-in, never on
//! install or upgrade — see `linux/packaging/setup/charter-applock`). charterd
//! only REPORTS it, and reports `true` only when every link that makes the
//! lock bite is present right now, so a guardian never reads "armed" off a
//! box where it is not:
//!
//! 1. the rendered rules file in `rules.d` is ours (first line carries the
//!    tag `charter-applock` writes),
//! 2. `compiled.rules` — what fapolicyd actually loads — carries the ward
//!    default-deny,
//! 3. `fapolicyd.conf` is not permissive,
//! 4. a `fapolicyd` process is alive (`/run/fapolicyd.pid` → `/proc/<pid>/comm`).
//!
//! Plain file reads only (no `systemctl` exec per tick); any unreadable link
//! reads as "not armed".

use std::fs;
use std::path::PathBuf;

/// First line of the rules file `charter-applock arm` renders. Mirrors
/// `GENERATED_TAG` in `charter-applock` — change both together.
pub const GENERATED_TAG: &str = "# generated by charter-applock";
/// The default-deny every rendered rules file carries. Mirrors `DENY_MARK`.
pub const DENY_MARK: &str = "deny_log perm=execute";

/// The four places the judgement reads, redirectable for tests.
#[derive(Debug, Clone)]
pub struct AppLockPaths {
    pub rules: PathBuf,
    pub compiled: PathBuf,
    pub conf: PathBuf,
    pub pid_file: PathBuf,
    pub proc_root: PathBuf,
}

impl Default for AppLockPaths {
    fn default() -> Self {
        Self {
            rules: "/etc/fapolicyd/rules.d/72-kintrinsic-applock.rules".into(),
            compiled: "/etc/fapolicyd/compiled.rules".into(),
            conf: "/etc/fapolicyd/fapolicyd.conf".into(),
            pid_file: "/run/fapolicyd.pid".into(),
            proc_root: "/proc".into(),
        }
    }
}

/// The rules file is the one `charter-applock` rendered.
pub fn rules_are_ours(rules: &str) -> bool {
    rules
        .lines()
        .next()
        .is_some_and(|l| l.starts_with(GENERATED_TAG))
}

/// fapolicyd would load a ward default-deny from this compiled rule set.
pub fn compiled_has_policy(compiled: &str) -> bool {
    compiled
        .lines()
        .any(|l| l.trim_start().starts_with(DENY_MARK))
}

/// `fapolicyd.conf` leaves fapolicyd ENFORCING: the last uncommented
/// `permissive = N` is 0, or there is none (fapolicyd's default is 0).
pub fn conf_is_enforcing(conf: &str) -> bool {
    let mut permissive: Option<&str> = None;
    for line in conf.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            if k.trim() == "permissive" {
                permissive = Some(v.trim());
            }
        }
    }
    matches!(permissive, None | Some("0"))
}

/// The pure judgement over the four links.
pub fn armed(rules: &str, compiled: &str, conf: &str, daemon_alive: bool) -> bool {
    daemon_alive
        && rules_are_ours(rules)
        && compiled_has_policy(compiled)
        && conf_is_enforcing(conf)
}

/// Read the live system. Any link missing or unreadable → `false`.
pub fn probe(paths: &AppLockPaths) -> bool {
    let read = |p: &PathBuf| fs::read_to_string(p).ok();
    let (Some(rules), Some(compiled), Some(conf)) =
        (read(&paths.rules), read(&paths.compiled), read(&paths.conf))
    else {
        return false;
    };
    let alive = read(&paths.pid_file)
        .and_then(|pid| pid.trim().parse::<u32>().ok())
        .and_then(|pid| fs::read_to_string(paths.proc_root.join(pid.to_string()).join("comm")).ok())
        .is_some_and(|comm| comm.trim() == "fapolicyd");
    armed(&rules, &compiled, &conf, alive)
}

#[cfg(test)]
mod tests {
    use super::*;

    const RULES: &str = "# generated by charter-applock — do not edit\n# wards (uid): 1001\ndeny_log perm=execute uid=1001 : all\n";
    const COMPILED: &str = "## This file is automatically generated from /etc/fapolicyd/rules.d\nallow perm=execute uid=1001 : dir=/usr/\ndeny_log perm=execute uid=1001 : all\nallow perm=any all : all\n";
    const CONF: &str = "#\n# permissive = 1\npermissive = 0\ntrust = file\n";

    #[test]
    fn every_link_present_is_armed() {
        assert!(armed(RULES, COMPILED, CONF, true));
    }

    #[test]
    fn any_missing_link_is_not_armed() {
        assert!(!armed(RULES, COMPILED, CONF, false), "daemon down");
        assert!(
            !armed("allow perm=any all : all\n", COMPILED, CONF, true),
            "someone else's rules file"
        );
        assert!(
            !armed(RULES, "allow perm=any all : all\n", CONF, true),
            "rules not compiled"
        );
        assert!(
            !armed(RULES, COMPILED, "permissive = 1\n", true),
            "permissive (the arm self-test state)"
        );
    }

    #[test]
    fn permissive_parsing_follows_fapolicyd() {
        assert!(conf_is_enforcing("trust = file\n"), "absent defaults to 0");
        assert!(conf_is_enforcing("# permissive = 1\npermissive=0\n"));
        assert!(
            !conf_is_enforcing("permissive = 0\npermissive = 1\n"),
            "last wins"
        );
        assert!(!conf_is_enforcing("  permissive =  1  \n"));
    }

    #[test]
    fn probe_reads_the_filesystem_and_fails_safe() {
        let dir = std::env::temp_dir().join(format!("charterd-app-lock-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(dir.join("proc/4242")).unwrap();
        let paths = AppLockPaths {
            rules: dir.join("rules"),
            compiled: dir.join("compiled"),
            conf: dir.join("conf"),
            pid_file: dir.join("pid"),
            proc_root: dir.join("proc"),
        };
        assert!(!probe(&paths), "nothing on disk");
        fs::write(&paths.rules, RULES).unwrap();
        fs::write(&paths.compiled, COMPILED).unwrap();
        fs::write(&paths.conf, CONF).unwrap();
        fs::write(&paths.pid_file, "4242\n").unwrap();
        assert!(!probe(&paths), "pid with no process");
        fs::write(dir.join("proc/4242/comm"), "bash\n").unwrap();
        assert!(!probe(&paths), "pid reused by another program");
        fs::write(dir.join("proc/4242/comm"), "fapolicyd\n").unwrap();
        assert!(probe(&paths));
        fs::remove_dir_all(&dir).unwrap();
    }

    /// The Rust constants and the shell script must agree, or charterd would
    /// report a correctly armed box as unarmed.
    #[test]
    fn constants_match_charter_applock() {
        let script = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../packaging/setup/charter-applock"),
        )
        .unwrap();
        assert!(script.contains(&format!("GENERATED_TAG=\"{GENERATED_TAG}\"")));
        assert!(script.contains(&format!("DENY_MARK=\"{DENY_MARK}\"")));
        let d = AppLockPaths::default();
        assert!(script.contains(&format!(
            "RULES_DST=\"$FAPO_DIR/rules.d/{}\"",
            d.rules.file_name().unwrap().to_str().unwrap()
        )));
    }
}
