//! Offline guardian unlock — a challenge/response the guardian's phone can
//! answer WITHOUT network, a memorized secret, or a synced clock, using the
//! guardian↔machine shared secret (the NIP-44 conversation key) that both sides
//! already hold from pairing.
//!
//! Flow: the locked-out ward device (charterd) shows a short CHALLENGE on the
//! lock screen. The guardian types it into MyCharter, which derives the same
//! shared secret from the guardian key + the device's pubkey and returns an
//! 8-digit CODE. charterd — which computed the expected code from the same
//! secret and passed it to `charter-lock` — compares and, on match, pauses
//! enforcement. The child cannot produce the code: they hold neither private
//! key, so they cannot derive the shared secret. A fresh challenge per lockout
//! means a shoulder-surfed code doesn't carry to the next lock.
//!
//! Construction (MUST match the TS mirror in MyCharter — see the shared test
//! vectors in both `unlock` test modules):
//! ```text
//!   secret = HMAC-SHA256(conv_key, "charter-offline-unlock-v1")   // domain sep
//!   mac    = HMAC-SHA256(secret, challenge_ascii_bytes)
//!   code   = HOTP (RFC 4226) dynamic truncation of `mac`, mod 10^8, 8 digits
//! ```
//! The domain-separation label means the unlock secret is never the raw
//! conversation key used for message encryption, so exposing an unlock code (or
//! the derived secret passed to `charter-lock`) never weakens the wire crypto.

use hmac::digest::KeyInit;
use hmac::{Hmac, Mac};
use sha2::Sha256;
use zeroize::Zeroizing;

type HmacSha256 = Hmac<Sha256>;

/// Domain-separation label for the unlock subkey (versioned).
const DOMAIN: &[u8] = b"charter-offline-unlock-v1";

/// Number of decimal digits in an unlock code (10^8 space; guessing is
/// infeasible under the lock's per-attempt rate limit).
pub const UNLOCK_CODE_DIGITS: usize = 8;

fn hmac_sha256(key: &[u8], msg: &[u8]) -> [u8; 32] {
    // HMAC accepts a key of any length, so `new_from_slice` never errors here.
    // hmac 0.13 moved `new_from_slice` off `Mac` onto `KeyInit`; `Mac` still
    // provides `update`/`finalize` below.
    let mut mac =
        <HmacSha256 as KeyInit>::new_from_slice(key).expect("HMAC accepts any key length");
    mac.update(msg);
    mac.finalize().into_bytes().into()
}

/// The expected unlock code for `challenge`, derived from the guardian↔machine
/// shared secret `conv_key` (the NIP-44 conversation key). Returns exactly
/// [`UNLOCK_CODE_DIGITS`] ASCII digits.
pub fn unlock_code(conv_key: &[u8; 32], challenge: &str) -> String {
    let secret = Zeroizing::new(hmac_sha256(conv_key, DOMAIN));
    let mac = hmac_sha256(&*secret, challenge.as_bytes());
    // RFC 4226 (HOTP) dynamic truncation: use the low nibble of the last byte
    // as an offset into the MAC and read a 31-bit big-endian integer there.
    let off = (mac[mac.len() - 1] & 0x0f) as usize;
    let bin = ((mac[off] & 0x7f) as u32) << 24
        | (mac[off + 1] as u32) << 16
        | (mac[off + 2] as u32) << 8
        | (mac[off + 3] as u32);
    let code = bin % 100_000_000;
    format!("{code:08}")
}

/// Constant-time comparison of a typed code against the expected one. Both are
/// short ASCII digit strings; compares without an early-out so a wrong guess
/// can't be refined by timing. A length mismatch is always a non-match.
pub fn code_matches(expected: &str, typed: &str) -> bool {
    let a = expected.as_bytes();
    let b = typed.as_bytes();
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    // SHARED PARITY VECTORS — these exact (conv_key, challenge) → code triples
    // are also asserted by the TS mirror (apps/charter-app/src/unlock.test.ts).
    // If you change the construction, regenerate BOTH. conv_key is 32 bytes hex.
    fn key(byte: u8) -> [u8; 32] {
        [byte; 32]
    }

    #[test]
    fn known_answer_vectors_match_ts_mirror() {
        // Generated by this implementation; the TS test asserts the same outputs.
        assert_eq!(unlock_code(&key(0x07), "K7QN"), "48437822");
        assert_eq!(unlock_code(&key(0x07), "4821"), "55118120");
        assert_eq!(unlock_code(&key(0x2a), "K7QN"), "92990140");
        let mut k = [0u8; 32];
        for (i, b) in k.iter_mut().enumerate() {
            *b = i as u8;
        }
        assert_eq!(unlock_code(&k, "HELLO"), "27854096");
    }

    #[test]
    fn code_is_eight_ascii_digits() {
        let c = unlock_code(&key(0x11), "abcd");
        assert_eq!(c.len(), UNLOCK_CODE_DIGITS);
        assert!(c.bytes().all(|b| b.is_ascii_digit()));
    }

    #[test]
    fn different_challenge_or_key_changes_the_code() {
        let a = unlock_code(&key(1), "K7QN");
        let b = unlock_code(&key(1), "K7QM");
        let c = unlock_code(&key(2), "K7QN");
        assert_ne!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn code_matches_is_constant_time_and_correct() {
        assert!(code_matches("00012345", "00012345"));
        assert!(!code_matches("00012345", "00012346"));
        assert!(!code_matches("00012345", "0001234")); // length mismatch
        assert!(!code_matches("00012345", ""));
    }
}
